
contact_links:
  - name: Update Roadmap
    url: https://trello.com/b/XGV1cvtb/bdo-planner-roadmap
    about: Find out features that we're planning on in the future.
  - name: Ask the community
    url: https://discord.bdoplanner.com/
    about: Ask and discuss questions with our community on Discord.