name: Feature request
about: Suggest an idea for BDO Planner
title: ''
labels: ["feature", "app"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to complete this feature request!
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our life a bit easier.
      options:
        - label: I have [searched](https://github.com/BDO-Planner/issues/issues) for duplicate or closed feature requests.
          required: true
        - label: I have read the [Common Feature Requests](https://github.com/BDO-Planner/issues/blob/master/README.md).
          required: true
        - label: I have read the [Roadmap](https://trello.com/b/XGV1cvtb/bdo-planner-roadmap) to check my feature isn't already planned.
          required: true
  - type: textarea
    id: feature-problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
  - type: textarea
    id: feature-solution
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen.